# Nombre del microservicio
spring.application.name=usuarios-service

# Puerto del backend
server.port=8082

# Configuración PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/usuarios_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Formatear SQL
spring.jpa.properties.hibernate.format_sql=true