# Nombre microservicio
spring.application.name=usuarios-service

# Puerto backend
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/usuarios_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=HikariPool-Usuarios

# JPA
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL
spring.jpa.show-sql=true

# Formatear SQL
spring.jpa.properties.hibernate.format_sql=true

# Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-hnxz55jjtq1inapb.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://libro-digital-api

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.academicoService.register-health-indicator=true
resilience4j.circuitbreaker.instances.academicoService.sliding-window-size=5
resilience4j.circuitbreaker.instances.academicoService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.academicoService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.academicoService.wait-duration-in-open-state=10s

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true