services:

  # Base de datos PostgreSQL para academico-service
  postgres-academico:
    image: postgres:16

    container_name: postgres-academico

    environment:
      POSTGRES_DB: academico_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_academico_data:/var/lib/postgresql/data

  # Base de datos PostgreSQL para usuarios-service
  postgres-usuarios:
    image: postgres:16

    container_name: postgres-usuarios

    environment:
      POSTGRES_DB: usuarios_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5434:5432"

    volumes:
      - postgres_usuarios_data:/var/lib/postgresql/data

  # Base de datos PostgreSQL para asistencia-notificacion-service
  postgres-asistencia:
    image: postgres:16

    container_name: postgres-asistencia

    environment:
      POSTGRES_DB: asistencia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5435:5432"

    volumes:
      - postgres_asistencia_data:/var/lib/postgresql/data

  # Cliente visual para administrar PostgreSQL
  pgadmin:
    image: dpage/pgadmin4

    container_name: pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres-academico
      - postgres-usuarios
      - postgres-asistencia

volumes:

  # Persistencia PostgreSQL academico-service
  postgres_academico_data:

  # Persistencia PostgreSQL usuarios-service
  postgres_usuarios_data:

  # Persistencia PostgreSQL asistencia-notificacion-service
  postgres_asistencia_data: