spring.application.name=asistencia-notificacion-service

server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5435/asistencia_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=AsistenciaHikariCP

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info

# Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-hnxz55jjtq1inapb.us.auth0.com/

spring.security.oauth2.resourceserver.jwt.audience=https://libro-digital-api