# Nombre del microservicio
spring.application.name=asistencia-notificacion-service

# Puerto del backend
server.port=8083

# Configuración PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5435/asistencia_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Formatear SQL
spring.jpa.properties.hibernate.format_sql=true

# Configuración Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Serializadores Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer