# Nombre del microservicio
spring.application.name=academico-service

# Puerto donde correrá este backend
server.port=8081

# Configuración de conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/academico_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=HikariPool-Academico

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true

# Formatear SQL mostrado en consola
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-hnxz55jjtq1inapb.us.auth0.com/

spring.security.oauth2.resourceserver.jwt.audience=https://libro-digital-api