# Nombre del microservicio
spring.application.name=academico-service

# Puerto donde correrá este backend
server.port=8081

# Configuración de conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/academico_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true

# Formatear SQL mostrado en consola
spring.jpa.properties.hibernate.format_sql=true